# Netlify configuration for a Next.js application.
# The Netlify build system will automatically detect and use the Next.js runtime.
[build]
  # The command to build the Next.js site.
  command = "npm run build"
  # The directory where the built site is located. For Next.js, this is .next.
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
