[build]
  publish = "dist"
  command = "rm -rf dist build node_modules/.cache && npm install && npm run build"

[functions]
  directory = "netlify/functions"
  # Function timeout settings
  external_node_modules = ["@google-cloud/secret-manager", "googleapis"]
  node_bundler = "esbuild"
  # Error handling and debugging
  included_files = ["netlify/functions/**/*.js"]

[build.environment]
  NODE_VERSION = "18"
  # NUCLEAR CACHE BUST - FORCE COMPLETE REBUILD
  SKIP_CACHE = "true"
  FORCE_REBUILD = "true"
  BUILD_VERSION = "netlify-functions-firebase-2025-01-19-FINAL-FIX"
  FIREBASE_ENABLED = "true"
  FUNCTIONS_ARCHITECTURE = "true"
  SECRET_MANAGER_SUPPORT = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Firebase-Status = "firebase-enabled"
    X-Build-Version = "netlify-functions-2025-01-19"
    X-Functions-Support = "enabled"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
