# Netlify configuration for a Next.js application.
# The Netlify build system will automatically detect and use the Next.js runtime.
[build]
  # The command to build the Next.js site.
  command = "node scripts/fetch-secrets.js && npm run build"
  # The directory where the built site is located. For Next.js, this is .next.
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Development server settings
[dev]
  # Command to start the Next.js development server
  command = "npm run dev"
  # The port will be automatically detected from the framework
  # Specify the framework to ensure correct handling
  framework = "next"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
