import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
// Ta bort import av Chat härifrån
// import { Chat } from '../components/Chat';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ByggPilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* Huvudinnehållet för sidan */}
          {children}
          {/* Chatten hanteras nu i respektive sidlayout igen */}
          {/* <Chat /> */}
        </Providers>
      </body>
    </html>
  );
}
